version: '3'
services:
  minio:
    container_name: storage
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./storage/minio:/data
    restart: always
    environment:
      MINIO_ROOT_USER: boilerplate
      MINIO_ROOT_PASSWORD: boilerplate@123
    command: server /data --console-address ":9001"
